---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r, warning=FALSE}
rm(list = ls())
library(rjags)
library(R2jags)
library(coda)
library(ggmcmc)
library(boot)
library(ggplot2)
library(magrittr)
library(dplyr)
library(RColorBrewer)
library(ggthemes)
library(scales)
library(glmnet)
library(HDInterval)
set.seed(2)
```



```{r}
data = list(rt = c(3, 7, 5, 102, 28, 4, 98, 60, 25, 138, 64, 45, 9, 57, 25, 33, 28, 8, 6, 32, 27, 22 ),
            nt = c(38, 114, 69, 1533, 355, 59, 945, 632, 278,1916, 873, 263, 291, 858, 154, 207, 251, 151, 174, 209, 391, 680),
            rc = c(3, 14, 11, 127, 27, 6, 152, 48, 37, 188, 52, 47, 16, 45, 31, 38, 12, 6, 3, 40, 43, 39),
            nc = c(39, 116, 93, 1520, 365, 52, 939, 471, 282, 1921, 583, 266, 293, 883, 147, 213, 122, 154, 134, 218, 364, 674),
            Num = 22)
```


```{r}
p_c = data$rt/data$nt
p_t = data$rc/data$nc
logit_pc = logit(p_c)
logit_pt = logit(p_t)
```

```{r}
# histogram of the logit of probailities observed
ggplot(data = data.frame(x = logit_pc), aes(x)) +
  theme_bw()+
  theme(plot.title = element_text(size = 15))+
  geom_histogram(bins = 5,
                 color = "blue3",
                 fill = "cornflowerblue")+
  labs(title = "Histogram of empirical log odds",subtitle = "Control Group", x = "Logit(p)", y = "Frequency")


ggplot(data = data.frame(x = logit_pt), aes(x)) +
  theme_bw() +
  theme(plot.title = element_text(size = 15))+
  geom_histogram(bins = 7,
                 color = "forestgreen",
                 fill = "darkolivegreen1")+
  labs(title = "Histogram of empirical log odds",subtitle = "Treatment Group", x = "Logit(p)", y = "Frequency")
```


```{r}
# prior distribution of mean and variance of delta
# plot of nu and precision tau
ggplot(data = data.frame(x = c(-1000, 1000)), aes(x)) + 
  theme_bw() + 
  theme(plot.title = element_text(size = 35), text = element_text(size=30))+
  stat_function(fun = dnorm, args = list(mean = 0, sd = 1/sqrt(10e-6)), size = 2, color = "red")+
  labs(title = expression(paste("Prior distribution of ", nu)), y = "Probability", x = expression(nu))


ggplot(data = data.frame(x = c(0.,1)), aes(x))+
  theme_bw() + 
  theme(plot.title = element_text(size = 35), text = element_text(size=30))+
  stat_function(fun = dgamma, args = list(shape = 0.001, rate = 0.001),size = 2, color = "blue")+
  labs(title = expression(paste("Prior distribution of ", tau)), y="Probability", x = expression(nu))

```


```{r}
# in order to plot the prior distribution of the random effect delta, just to have an idea of how it looks like, i can evaluate the expected value of nu and sigma2 and use those value as parameter in the Normal distribution of delta (random effect)

# We already know that the expected value in a normal distribution is just the mean (0 in case of nu)
# The only thing left is the expected value of the gamma distribution (expected value of the variance sigma2)

# The expected value of Gamma distribution is E = shape/rate = 0.001/0.001 = 1

# The prior distribution of delta random effect will be the a Normal(0,1)

ggplot(data = data.frame(x = c(-3, 3)), aes(x)) + 
  theme_bw() +
  theme(plot.title = element_text(size = 35), text = element_text(size=30))+
  stat_function(fun = dnorm, args = list(mean = 0, sd = 1), size=2, color = "green") +
  labs(title = expression(paste("Prior distribution of " , delta )), x = expression(delta), y = "Probability" )

```

# Model 1

```{r}
model1 = "
      model
      {
         for( i in 1 : Num ) {
            rc[i] ~ dbin(pc[i], nc[i])
            rt[i] ~ dbin(pt[i], nt[i])
            logit(pc[i]) <- mu[i]
            logit(pt[i]) <- mu[i] + delta[i]
            mu[i] ~ dnorm(0.0,1.0E-5)
            delta[i] ~ dnorm(nu, tau)
         }
         nu ~ dnorm(0.0,1.0E-6)
         tau ~ dgamma(0.001,0.001)
         delta.new ~ dnorm(nu, tau)
         sigma <- 1 / sqrt(tau)
      }"

writeLines( model1 , con="m1" )
```

```{r}
init = function() list("nu" = 0,     # mean of random effect delta
             "delta.new" = 0,   # value coming from the predictive distribution of delta
             "tau"=1,           # prior precision of Normal distribution of delta
             "mu" = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), # 0 mu for all the cases
             "delta" = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)) # no random effect 

params = c("nu", "delta.new", "tau","mu", "delta")
```

```{r}
Model1 = jags( model.file="m1" , data=data , inits=init , 
               n.chains=3,parameters.to.save = params[1:3] ,
               n.iter =20000,n.thin=1,n.burnin = 2000)
```

```{r}
Model1
```

```{r}
# traceplot, running mean, posterior density
gg_model1 = ggs(as.mcmc(Model1))

# traceplot of parameters of interest
ggs_traceplot(gg_model1, greek = TRUE)+   
  theme_bw()

# traceplot of running mean
ggs_running(gg_model1, greek = TRUE)+
  theme_bw()

# plot posterior density
ggs_density(gg_model1, greek = TRUE)+
  theme_bw()
```






```{r}
matplot(seq(50), Model1$BUGSoutput$sims.array[,,2][0:50,], type = "b", pch = 16, lty = 1,main = "Zoom on deviance",xlab = "Iteration", ylab = "Deviance",xaxt = "n", col = c("firebrick1", "springgreen2","lightslateblue"))
axis(1, at = seq(50), labels = paste(seq(50)))
legend("topright", legend = c("Chain 1", "Chain 2", "Chain 3"), col = c("firebrick1", "springgreen2","lightslateblue"), pch = c(16,16,16), lty = c(1,1,1))
grid()


matplot(seq(100,1000), Model1$BUGSoutput$sims.array[,,2][100:1000,], type = "l", pch = 16, lty = 1,main = "Zoom on deviance",xlab = "Iteration", ylab = "Deviance",xaxt = "n", col = c("firebrick1", "springgreen2","lightslateblue"))
axis(1, at = seq(100,1000, 50), labels = paste(seq(100,1000, 50)))
legend("topright", legend = c("Chain 1", "Chain 2", "Chain 3"), col = c("firebrick1", "springgreen2","lightslateblue"), pch = c(16,16,16), lty = c(1,1,1), cex = .6)
grid()
```



```{r}
# evaluate the autocorrelation of all the parameters for the 3 chains
autocorrelated_delta_new = apply(Model1$BUGSoutput$sims.array[,,1], 2, acf, lag.max = 18000, plot = FALSE)
autocorrelated_deviance  = apply(Model1$BUGSoutput$sims.array[,,2], 2, acf, lag.max = 18000, plot = FALSE)
autocorrelated_nu        = apply(Model1$BUGSoutput$sims.array[,,3], 2, acf, lag.max = 18000, plot = FALSE)
autocorrelated_tau       = apply(Model1$BUGSoutput$sims.array[,,4], 2, acf, lag.max = 18000, plot = FALSE)

# attach the acf values of 3 chain in a unique matrix for each parameter
autocorrelated_delta_new = cbind(c(autocorrelated_delta_new[[1]]$acf),
                                 c(autocorrelated_delta_new[[2]]$acf),
                                 c(autocorrelated_delta_new[[3]]$acf))

autocorrelated_deviance  = cbind(c(autocorrelated_deviance[[1]]$acf),
                                 c(autocorrelated_deviance[[2]]$acf),
                                 c(autocorrelated_deviance[[3]]$acf))

autocorrelated_nu        = cbind(c(autocorrelated_nu[[1]]$acf),
                                 c(autocorrelated_nu[[2]]$acf),
                                 c(autocorrelated_nu[[3]]$acf))

autocorrelated_tau       = cbind(c(autocorrelated_tau[[1]]$acf),
                                 c(autocorrelated_tau[[2]]$acf),
                                 c(autocorrelated_tau[[3]]$acf))
```

```{r}
# delta new
matplot(seq(18000), autocorrelated_delta_new, type = "l", pch = 16, lty = 1,
        main = expression(paste(delta, " new autocorrelation")),
        xlab = "Iteration", ylab = "Deviance",xaxt = "n", 
        col = c("firebrick1", "springgreen2","lightslateblue"), ylim = c(-0.1, 0.1))
axis(1, at = seq(18000), labels = paste(seq(18000)))
legend("topright", legend = c("Chain 1", "Chain 2", "Chain 3"), 
       col = c("firebrick1", "springgreen2","lightslateblue"), 
       pch = c(16,16,16), lty = c(1,1,1), cex = .6)
grid()


# deviance
matplot(seq(18000), autocorrelated_deviance, type = "l", pch = 16, lty = 1,
        main = expression(paste("Deviance autocorrelation")),
        xlab = "Iteration", ylab = "Deviance",xaxt = "n",
        col = c("firebrick1", "springgreen2","lightslateblue"), ylim = c(-0.1, 0.1))
axis(1, at = seq(18000), labels = paste(seq(18000)))
legend("topright", legend = c("Chain 1", "Chain 2", "Chain 3"), 
       col = c("firebrick1", "springgreen2","lightslateblue"), 
       pch = c(16,16,16), lty = c(1,1,1), cex = .6)
grid()


# nu
matplot(seq(18000), autocorrelated_nu, type = "l", pch = 16, lty = 1,
        main = expression(paste(nu, " autocorrelation")),
        xlab = "Iteration", ylab = "Deviance",xaxt = "n", 
        col = c("firebrick1", "springgreen2","lightslateblue"), ylim = c(-0.1, 0.1))
axis(1, at = seq(18000), labels = paste(seq(18000)))
legend("topright", legend = c("Chain 1", "Chain 2", "Chain 3"), 
       col = c("firebrick1", "springgreen2","lightslateblue"), 
       pch = c(16,16,16), lty = c(1,1,1), cex = .6)
grid()


# tau
matplot(seq(18000), autocorrelated_tau, type = "l", pch = 16, lty = 1,
        main = expression(paste(tau, " autocorrelation")),
        xlab = "Iteration", ylab = "Deviance",xaxt = "n",
        col = c("firebrick1", "springgreen2","lightslateblue"), ylim = c(-0.1, 0.1))
axis(1, at = seq(18000), labels = paste(seq(18000)))
legend("topright", legend = c("Chain 1", "Chain 2", "Chain 3"), 
       col = c("firebrick1", "springgreen2","lightslateblue"), 
       pch = c(16,16,16), lty = c(1,1,1), cex = .6)
grid()
```




```{r}
# save in appropriate variable 
delta.new_posterior = Model1$BUGSoutput$summary[1,1]
nu_posterior        = Model1$BUGSoutput$summary[3,1]
sigma_posterior     = 1/sqrt(Model1$BUGSoutput$summary[4,1])
```


```{r}
# having some estimates for the parameters nu and tau (mean and variance of the random effect delta respectively) is it possible to plot the original distribution declared in the model with the new parameters found with MCMC procedure
ggplot(data = data.frame(x = c(-2.5, 2.5)), aes(x)) +
  theme_bw()+
  theme(plot.title = element_text(size = 15), text = element_text(size=12))+
  stat_function(fun = dnorm, args = list(mean = 0, sd = 1), aes(colour = "Prior")) +
  stat_function(fun = dnorm, args = list(mean = nu_posterior, sd = sigma_posterior), aes(colour="Posterior")) +
  labs(title = expression(paste("Prior and posterior distribution of random effect ",delta)), subtitle = "Model 1")+
  geom_vline(xintercept = 0, colour = "darkgrey", linetype = "longdash")+
  geom_vline(xintercept = nu_posterior, colour = "deepskyblue", linetype = "longdash")+
  scale_colour_manual("Distrubtutions", 
                      breaks = c("Prior", "Posterior"),
                      values = c("deepskyblue3", "dimgrey"))
```


# Model 2


```{r}
model2 = "model
    {
       for( i in 1 : Num ) {
          rc[i] ~ dbin(pc[i], nc[i])
          rt[i] ~ dbin(pt[i], nt[i])
          logit(pc[i]) <- mu[i]
          logit(pt[i]) <- mu[i] + delta[i]
          mu[i] ~ dnorm(0.0,1.0E-5)
          delta[i] ~ dt(nu, tau, 3)
       }
       nu ~ dnorm(0.0,1.0E-6)
       tau ~ dgamma(0.001,0.001)
       delta.new ~ dt(nu, tau, 3)
       sigma <- 1 / sqrt(tau)
    }"

writeLines( model2 , con="m2" )

init = function() list("nu" = 0,        # mean of random effect delta
                       "delta.new" = 0, # value coming from the predictive distribution of delta
                       "tau"=1,         # prior precision of Normal distribution of delta
                       "mu" = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), # 0 mu for all the cases
                       "delta" = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)) # no random effect 

params = c("nu", "delta.new", "tau","mu", "delta")


Model2 = jags( model.file="m2" , data=data , inits=init , 
               n.chains=3,parameters.to.save = params[1:3] ,
               n.iter =20000,n.thin=1,n.burnin = 2000)
```

```{r}
Model2
```

```{r non-standardized t-Student}
ns_t = function(x, mu, tau, k){
  # x   = values
  # mu  = mean
  # tau = precision
  # k   = degree of freedom
  ( gamma((k+1)/2)/gamma(k/2) )*( sqrt(tau/(k*pi)) )*( (1+(tau*(x-mu)^2/k))^(-k+1/2) )
}
```



```{r}
# prior distribution of delta
ggplot(data = data.frame(x = c(-5, 5)), aes(x)) + 
  theme_bw() + 
  theme(plot.title = element_text(size = 15), text = element_text(size=15))+
  stat_function(fun = ns_t, args = list(mu=0, tau = 1, k = 3), size = 0.5, aes(colour = "Model2")) + 
  stat_function(fun = dnorm, args = list(mean = 0, sd = 1), size = 0.5, aes(colour = "Model1"))+
  xlim(-5,5)+
  labs(title = expression(paste("Prior distribution of ", delta)), y = "Probability", x = expression(delta))+
  scale_colour_manual("Priors", 
                    breaks = c("Model1", "Model2"),
                    values = c("red", "dimgrey"))
```

```{r}
# zoom left tail
ggplot(data = data.frame(x = c(-5, 5)), aes(x)) + 
  theme_bw() + 
  theme(plot.title = element_text(size = 15), text = element_text(size=10))+
  stat_function(fun = ns_t, args = list(mu=0, tau = 1, k = 3), size = 0.5, aes(colour = "Model2")) + 
  stat_function(fun = dnorm, args = list(mean = 0, sd = 1), size = 0.5, aes(colour = "Model1"))+
  xlim(-10,-5)+
  labs(title = expression(paste("Zoom on priors tails")), subtitle = "Left tail", y = "Probability", x = expression(delta))+
  scale_colour_manual("Priors", 
                    breaks = c("Model1", "Model2"),
                    values = c("red", "dimgrey"))


# zoom right tail
ggplot(data = data.frame(x = c(-5, 5)), aes(x)) + 
  theme_bw() + 
  theme(plot.title = element_text(size = 15), text = element_text(size=10))+
  stat_function(fun = ns_t, args = list(mu=0, tau = 1, k = 3), size = 0.5, aes(colour = "Model2")) + 
  stat_function(fun = dnorm, args = list(mean = 0, sd = 1), size = 0.5, aes(colour = "Model1"))+
  xlim(5,10)+
  labs(title = expression(paste("Zoom on priors tails")), subtitle = "Right tail", y = "Probability", x = expression(delta))+
  scale_colour_manual("Priors", 
                    breaks = c("Model1", "Model2"),
                    values = c("red", "dimgrey"))
```

```{r}
ggplot(data = data.frame(x = c(1, 1000)), aes(x)) + 
  theme_bw() + 
  theme(plot.title = element_text(size = 15), text = element_text(size=12))+
  stat_function(fun = ns_t, args = list(mu=0, tau = 1, k = 3), size = 0.5, aes(colour = "Model2")) + 
  stat_function(fun = dnorm, args = list(mean = 0, sd = 1), size = 0.5, aes(colour = "Model1"))+
 scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
        labels = trans_format("log10", math_format(10^.x))) +
 scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
          labels = trans_format("log10", math_format(10^.x))) +
  labs(title = expression(paste("Zoom on prior right tail")),subtitle = "Log-Log scale", y = "Probability", x = expression(delta))+
  scale_colour_manual("Priors", 
                    breaks = c("Model1", "Model2"),
                    values = c("red", "dimgrey"))
```


```{r}
# traceplot, running mean, posterior density
gg_model2 = ggs(as.mcmc(Model2))

# traceplot of parameters of interest
ggs_traceplot(gg_model2, greek = TRUE)+   
  theme_bw()

# traceplot of running mean
ggs_running(gg_model2, greek = TRUE)+
  theme_bw()

# plot posterior density
ggs_density(gg_model2, greek = TRUE)+
  theme_bw()
```

```{r}
# evaluate the autocorrelation of all the parameters for the 3 chains
autocorrelated_delta_new2 = apply(Model2$BUGSoutput$sims.array[,,1], 2, acf, lag.max = 18000, plot = FALSE)
autocorrelated_deviance2  = apply(Model2$BUGSoutput$sims.array[,,2], 2, acf, lag.max = 18000, plot = FALSE)
autocorrelated_nu2        = apply(Model2$BUGSoutput$sims.array[,,3], 2, acf, lag.max = 18000, plot = FALSE)
autocorrelated_tau2       = apply(Model2$BUGSoutput$sims.array[,,4], 2, acf, lag.max = 18000, plot = FALSE)

# attach the acf values of 3 chain in a unique matrix for each parameter
autocorrelated_delta_new2 = cbind(c(autocorrelated_delta_new2[[1]]$acf),
                                  c(autocorrelated_delta_new2[[2]]$acf),
                                  c(autocorrelated_delta_new2[[3]]$acf))

autocorrelated_deviance2  = cbind(c(autocorrelated_deviance2[[1]]$acf),
                                  c(autocorrelated_deviance2[[2]]$acf),
                                  c(autocorrelated_deviance2[[3]]$acf))

autocorrelated_nu2        = cbind(c(autocorrelated_nu2[[1]]$acf),
                                  c(autocorrelated_nu2[[2]]$acf),
                                  c(autocorrelated_nu2[[3]]$acf))

autocorrelated_tau2       = cbind(c(autocorrelated_tau2[[1]]$acf),
                                  c(autocorrelated_tau2[[2]]$acf),
                                  c(autocorrelated_tau2[[3]]$acf))
```

```{r}
# delta new
matplot(seq(18000), autocorrelated_delta_new2, type = "l", pch = 16, lty = 1,
        main = expression(paste(delta, " new autocorrelation")),
        xlab = "Iteration", ylab = "Deviance",xaxt = "n", 
        col = c("firebrick1", "springgreen2","lightslateblue"), ylim = c(-0.1, 0.1))
axis(1, at = seq(18000), labels = paste(seq(18000)))
legend("topright", legend = c("Chain 1", "Chain 2", "Chain 3"), 
       col = c("firebrick1", "springgreen2","lightslateblue"), 
       pch = c(16,16,16), lty = c(1,1,1), cex = .6)
grid()


# deviance
matplot(seq(18000), autocorrelated_deviance2, type = "l", pch = 16, lty = 1,
        main = expression(paste("Deviance autocorrelation")),
        xlab = "Iteration", ylab = "Deviance",xaxt = "n",
        col = c("firebrick1", "springgreen2","lightslateblue"), ylim = c(-0.1, 0.1))
axis(1, at = seq(18000), labels = paste(seq(18000)))
legend("topright", legend = c("Chain 1", "Chain 2", "Chain 3"), 
       col = c("firebrick1", "springgreen2","lightslateblue"), 
       pch = c(16,16,16), lty = c(1,1,1), cex = .6)
grid()


# nu
matplot(seq(18000), autocorrelated_nu2, type = "l", pch = 16, lty = 1,
        main = expression(paste(nu, " autocorrelation")),
        xlab = "Iteration", ylab = "Deviance",xaxt = "n", 
        col = c("firebrick1", "springgreen2","lightslateblue"), ylim = c(-0.1, 0.1))
axis(1, at = seq(18000), labels = paste(seq(18000)))
legend("topright", legend = c("Chain 1", "Chain 2", "Chain 3"), 
       col = c("firebrick1", "springgreen2","lightslateblue"), 
       pch = c(16,16,16), lty = c(1,1,1), cex = .6)
grid()


# tau
matplot(seq(18000), autocorrelated_tau2, type = "l", pch = 16, lty = 1,
        main = expression(paste(tau, " autocorrelation")),
        xlab = "Iteration", ylab = "Deviance",xaxt = "n",
        col = c("firebrick1", "springgreen2","lightslateblue"), ylim = c(-0.1, 0.1))
axis(1, at = seq(18000), labels = paste(seq(18000)))
legend("topright", legend = c("Chain 1", "Chain 2", "Chain 3"), 
       col = c("firebrick1", "springgreen2","lightslateblue"), 
       pch = c(16,16,16), lty = c(1,1,1), cex = .6)
grid()
```

```{r}
delta.new_posterior2 = Model2$BUGSoutput$summary[1,1]
nu_posterior2        = Model2$BUGSoutput$summary[3,1]
tau_posterior2       = Model2$BUGSoutput$summary[4,1]
```



```{r}
ggplot(data = data.frame(x = c(-2.5, 2.5)), aes(x)) +
  theme_bw()+
  theme(plot.title = element_text(size = 15), text = element_text(size=12))+
  stat_function(fun = ns_t, args = list(mu=0, tau = 1, k = 3), size = 1, aes(colour = "Prior")) +
  stat_function(fun = ns_t, args = list(mu=nu_posterior2, tau = tau_posterior2, k = 3), size = 1, aes(colour = "Posterior")) +
  labs(title = expression(paste("Prior and posterior distribution of random effect ",delta)), subtitle = "Model 2")+
  geom_vline(xintercept = 0, colour = "darkgrey", linetype = "longdash")+
  geom_vline(xintercept = nu_posterior, colour = "deepskyblue", linetype = "longdash")+
  scale_colour_manual("Distrubtutions", 
                      breaks = c("Prior", "Posterior"),
                      values = c("deepskyblue3", "dimgrey"))
```

# model 3

```{r}
set.seed(2)
#log( (data$rt/(data$nt-data$rt))/(data$rc/(data$nc-data$rc)) )

blocker<-read.csv("BLOCKER.csv", sep=",", header=T)
Nstud<-22

blockerDat <- list(Y=blocker$Y,V=blocker$V,Nstud=Nstud)
blockerParams <- c("d","tau","OR", "prob.OR1")
blockerInits<-function(){
  list("delta"=c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
       "d"=c(0),
       "tau"=c(1))
}


cat("model {

# Likelihood

for (j in 1:Nstud) {
    P[j] <- 1/V[j]      # Calculate precision
    Y[j] ~ dnorm(delta[j],P[j])
    delta[j] ~ dnorm(d,prec)
}

                        # Priors
d ~ dnorm(0,1.0E-6)
prec <- 1/tau.sq
tau.sq <- tau*tau   # tau.sq = between-study variance
tau ~ dunif(0,10)   # Uniform on SD
OR<-exp(d)          #exponentiate to get back to OR scale
prob.OR1<-step(d)   #calc prob of OR > 1
}", file="m3.txt")



jag.blocker1<-jags(data=blockerDat, 
                   inits=blockerInits, 
                   parameters.to.save=blockerParams, n.iter=20000, n.thin=1,
                   n.burnin = 2000,
                   model.file="m3.txt")

jag.blocker1
```

```{r}
# traceplot, running mean, posterior density
gg_model3 = ggs(as.mcmc(jag.blocker1))

# traceplot of parameters of interest
ggs_traceplot(gg_model3, greek = TRUE)+   
  theme_bw()

# traceplot of running mean
ggs_running(gg_model3, greek = TRUE)+
  theme_bw()

# plot posterior density
ggs_density(gg_model3, greek = TRUE)+
  theme_bw()
```

```{r}
# evaluate the autocorrelation of all the parameters for the 3 chains
autocorrelated_OR         = apply(jag.blocker1$BUGSoutput$sims.array[,,1], 2, acf, lag.max = 18000, plot = FALSE)
autocorrelated_d          = apply(jag.blocker1$BUGSoutput$sims.array[,,2], 2, acf, lag.max = 18000, plot = FALSE)
autocorrelated_deviance3  = apply(jag.blocker1$BUGSoutput$sims.array[,,3], 2, acf, lag.max = 18000, plot = FALSE)
autocorrelated_tau3       = apply(jag.blocker1$BUGSoutput$sims.array[,,5], 2, acf, lag.max = 18000, plot = FALSE)

# attach the acf values of 3 chain in a unique matrix for each parameter
autocorrelated_OR        = cbind(c(autocorrelated_OR[[1]]$acf),
                                 c(autocorrelated_OR[[2]]$acf),
                                 c(autocorrelated_OR[[3]]$acf))

autocorrelated_d         = cbind(c(autocorrelated_d[[1]]$acf),
                                 c(autocorrelated_d[[2]]$acf),
                                 c(autocorrelated_d[[3]]$acf))

autocorrelated_deviance3 = cbind(c(autocorrelated_deviance3[[1]]$acf),
                                 c(autocorrelated_deviance3[[2]]$acf),
                                 c(autocorrelated_deviance3[[3]]$acf))

autocorrelated_tau3      = cbind(c(autocorrelated_tau3[[1]]$acf),
                                 c(autocorrelated_tau3[[2]]$acf),
                                 c(autocorrelated_tau3[[3]]$acf))
```


```{r}
matplot(seq(18000), autocorrelated_OR, type = "l", pch = 16, lty = 1,
        main = expression(paste("OR new autocorrelation")),
        xlab = "Iteration", ylab = "Deviance",xaxt = "n", 
        col = c("firebrick1", "springgreen2","lightslateblue"), ylim = c(-0.1, 0.1))
axis(1, at = seq(18000), labels = paste(seq(18000)))
legend("topright", legend = c("Chain 1", "Chain 2", "Chain 3"), 
       col = c("firebrick1", "springgreen2","lightslateblue"), 
       pch = c(16,16,16), lty = c(1,1,1), cex = .6)
grid()


# deviance
matplot(seq(18000), autocorrelated_d, type = "l", pch = 16, lty = 1,
        main = expression(paste("d autocorrelation in model 3")),
        xlab = "Iteration", ylab = "Deviance",xaxt = "n",
        col = c("firebrick1", "springgreen2","lightslateblue"), ylim = c(-0.1, 0.1))
axis(1, at = seq(18000), labels = paste(seq(18000)))
legend("topright", legend = c("Chain 1", "Chain 2", "Chain 3"), 
       col = c("firebrick1", "springgreen2","lightslateblue"), 
       pch = c(16,16,16), lty = c(1,1,1), cex = .6)
grid()


# nu
matplot(seq(18000), autocorrelated_deviance3, type = "l", pch = 16, lty = 1,
        main = expression(paste("Deviance autocorrelation in model 3")),
        xlab = "Iteration", ylab = "Deviance",xaxt = "n", 
        col = c("firebrick1", "springgreen2","lightslateblue"), ylim = c(-0.1, 0.1))
axis(1, at = seq(18000), labels = paste(seq(18000)))
legend("topright", legend = c("Chain 1", "Chain 2", "Chain 3"), 
       col = c("firebrick1", "springgreen2","lightslateblue"), 
       pch = c(16,16,16), lty = c(1,1,1), cex = .6)
grid()


# tau
matplot(seq(18000), autocorrelated_tau3, type = "l", pch = 16, lty = 1,
        main = expression(paste(tau, " autocorrelation in model 3")),
        xlab = "Iteration", ylab = "Deviance",xaxt = "n",
        col = c("firebrick1", "springgreen2","lightslateblue"), ylim = c(-0.1, 0.1))
axis(1, at = seq(18000), labels = paste(seq(18000)))
legend("topright", legend = c("Chain 1", "Chain 2", "Chain 3"), 
       col = c("firebrick1", "springgreen2","lightslateblue"), 
       pch = c(16,16,16), lty = c(1,1,1), cex = .6)
grid()
```


# hypotheys testing for odds ratio significance

```{r}
# create contingency matrix
create_contingency = function(event_control,notevent_control,event_treat,notevent_treat){
  mat = matrix(data = c(event_control, notevent_control,event_treat,notevent_treat), ncol = 2, nrow = 2, byrow =T)
  return(mat)
  }

# transform the data in 2x2 contingency table
to_2x2 = function(count_control, n_control, count_treat, n_treat){
  
  not_event_control = n_control-count_control
  not_event_treat = n_treat-count_treat
  
  contingency_tables = list()
  
  for (i in 1:length(not_event_treat)){
    contingency_tables[[i]] = create_contingency(count_control[i], 
                                                 not_event_control[i], 
                                                 count_treat[i], 
                                                 not_event_treat[i])
  }
  return(contingency_tables)
}

# get p-value from fisher.test object
get_fisher_pvalue = function(table){
  return(fisher.test(table)$p.value)
}

get_chisquare_pvalue = function(table){
  return(chisq.test(table)$p.value)
}
```


```{r}
contingency_matrices = to_2x2(data$nc, data$nc, data$rt, data$nt) 
```

```{r}
fisher_results = lapply(contingency_matrices, get_fisher_pvalue)
fisher_results = unlist(fisher_results)
```

```{r}
chisquare_results = lapply(contingency_matrices, get_chisquare_pvalue)
chisquare_results = unlist(chisquare_results)
```


```{r}
cbind(rep(1:22), fisher_results, chisquare_results)
```


# Frequentist logistic regression

```{r}
Model1_single_trial = jags( model.file="m1" , data=data , inits=init , 
                            n.chains=3,parameters.to.save = params[3:5] ,
                            n.iter =20000,n.thin=1,n.burnin = 2000)

Model2_single_trial = jags( model.file="m2" , data=data , inits=init , 
                            n.chains=3,parameters.to.save = params[3:5] ,
                            n.iter =20000,n.thin=1,n.burnin = 2000)
```




```{r}
mu_trials = Model1_single_trial$BUGSoutput$summary[24:45,1]
delta_trials = Model1_single_trial$BUGSoutput$summary[1:22,1]

mu2_trials = Model2_single_trial$BUGSoutput$summary[24:45,1]
delta2_trials = Model2_single_trial$BUGSoutput$summary[1:22,1]


bayesian_pt = inv.logit(mu_trials + delta_trials)
bayesian_pc = inv.logit(mu_trials)

bayesian_pt2 = inv.logit(mu2_trials + delta2_trials)
bayesian_pc2 = inv.logit(mu2_trials)

cbind(p_t, bayesian_pt, bayesian_pt2)
cbind(p_c, bayesian_pc, bayesian_pc2)
```



```{r}
ggplot(data = data.frame(x = logit_pc), aes(x)) +
  theme_bw()+
  theme(plot.title = element_text(size = 15))+
  labs(title = "Densities of empirical and posterior bayesian log odds ",subtitle = "Control Group", x = "Logit(p)", y = "Density")+
  geom_density(aes(logit(bayesian_pc2)), colour = "red", fill = "red", alpha = 0.2)+
  geom_density(aes(logit(bayesian_pc)), colour = "green", fill = "green", alpha = 0.2)+
  geom_density(aes(logit_pc), colour = "cyan", fill = "cyan", alpha = 0.2)


ggplot(data = data.frame(x = logit_pt), aes(x)) +
  theme_bw() +
  theme(plot.title = element_text(size = 15))+
  labs(title = "Densities of empirical and posterior bayesian log odds ",subtitle = "Treatment Group", x = "Logit(p)", y = "Density")+
  geom_density(aes(logit(bayesian_pt2)) , colour = "red", fill = "red", alpha = 0.2)+
  geom_density(aes(logit(bayesian_pt)), colour = "green", fill = "green", alpha = 0.2)+
  geom_density(aes(logit_pt), colour = "cyan", fill = "cyan", alpha = 0.2 )

```












```{r}
group = c(rep("Treat",22), rep("Control", 22))
log_reg  = lm(c(logit_pt, logit_pc)~group) # log odds probability level
prob_reg = lm(c(p_t, p_c)~group)           # probability level
```

```{r}
summary(log_reg)
```

```{r}
summary(prob_reg)
```


```{r}
plot(x = as.factor(group), y = c(logit_pt, logit_pc), main = "Distribution of log odds wrt to Group",ylab = "logit(p)")
grid()
```



```{r}
# hdi_delta_new = hdi(as.mcmc(Model1$BUGSoutput$sims.array[,1,1]))
# plot(density(Model1$BUGSoutput$sims.array[,1,1]),main = expression(paste("Posterior Density Plot of ", delta)),lwd=2, xlab = expression(delta))
# abline(v=hdi_delta_new[1],col='blue', lwd=1.5)
# abline(v=hdi_delta_new[2],col='blue', lwd=1.5)
# abline(v=coef(log_reg)[2], col = "orange", lwd = 1.5)
# legend("topright", legend = c("Lower/Upper hdi", "Frequentist estimate"), col = c("blue", "orange"), lty = c(1, 1), lwd = c(1.5, 1.5), cex = 0.6)
# grid()
```


```{r}
# frequentist crude estimation of delta 
# freq_delta_estimation = coef(log_reg)[2]
# estimates = cbind(freq_delta_estimation, Model1$BUGSoutput$summary[1,1], Model2$BUGSoutput$summary[1,1])
# colnames(estimates) = c("Frequentist", "Bayesian m1", "Bayesian m2")
# rownames(estimates) = ""
# estimates
```

